name: DockerHubBuild
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 03:10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin 
    - name: Build Image red-gotools
      run: |
        docker build . --file ./src/Dockerfile \
          --tag ${{ secrets.DOCKERHUB_ORGANIZATION  }}/red-gotools
          --tag ${{ secrets.DOCKERHUB_ORGANIZATION  }}/red-gotools:latest
    - name: Push ocpredshift/red-gotools
      run: |
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION  }}/red-gotools \
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION  }}/red-gotools:latest
